// <auto-generated />
using Fipe.Compare.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Fipe.Compare.Context.Migrations
{
    [DbContext(typeof(FipeCompareContext))]
    partial class FipeCompareContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Fipe.Compare.Domain.Entitys.Motocycle", b =>
                {
                    b.Property<Guid>("IdMotocycle")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.HasKey("IdMotocycle");

                    b.ToTable("Motocycle");
                });
#pragma warning restore 612, 618
        }
    }
}
